<?php

/**
 * implementation of hook_panels_layouts()
 */
// Plugin definition
$plugin = array(
  'title' => t('Main'),
  'category' => t('Jim Birch'),
  'icon' => 'main.png',
  'theme' => 'panels-main',
  'css' => 'main.css',
  'regions' => array(
      'row-1' => t('Row 1'),
      'row-2' => t('Row 2'),
      'row-3' => t('Row 3'),
      'row-4' => t('Row 4'),
      'row-5' => t('Row 5'),
      'row-6' => t('Row 6'),
      'row-7' => t('Row 7'),
      'row-8' => t('Row 8'),
      'row-9' => t('Row 9'),
      'row-10' => t('Row 10'),
      'row-11' => t('Row 11'),
      'row-12' => t('Row 12'),
      'row-13' => t('Row 13'),
      'row-14' => t('Row 14'),
      'row-15' => t('Row 15'),
      'row-16' => t('Row 16'),
      'row-17' => t('Row 17'),
      'row-18' => t('Row 18')
  ),
);
